### PR TITLE
add option for alternative releases and app directories

### PR DESCRIPTION
**Pull request by GerritSommer**
Hello, 
I hope this PR is fine. If not i'd be happy if you tell me whats missing.
this PR just adds the option to customize the remote folders for the releases and the public folder. The folder you used staticly would be now the default values.

### CODE REVIEW

**Comment by youroff** [comment]
Thank you for this PR. It looks good so far, but there are couple of remarks. First off, could you revert the default value for applicationDir? It was `current`, now `public`, will definitely break the deploy for all users. Also, I'm not sure that `applicationDir` is a good name, since it's not really a dir, but rather a symlink. Any better ideas?

**Comment by GerritSommer** [comment]
Ahh yeah, my mistake. I accidently changed it to my needs, which is why I wanna make this PR.
I will change that. What do you think of "applicationDestination"?.
Before looking into the source I had the problem as well, that I didn't know it was a symlink, so I already created a 'current' folder and it added the symlink inside of it.
I would add a description explaining its a symlink to the README, if thats fine with you.

**Comment by youroff** [comment]
Oh, I thought it was like a super common practice, but yeah, a couple of words in readme would work. `applicationDestination` feels a bit long and doesn't reflect that its a link. Maybe something like `activeLink`, `activeRelease` or `targetLink`?

**Comment by GerritSommer** [comment]
Our Server-people use '/current/public' with all services and I don't feel in the position to tell them in such detail what to do or to change the directories of all servers.
So 'targetLink' sounds good to me. I will adapt the PR and commit later.

And thank you for your quick answers.

**Pull request merged**
