### PR TITLE
Add ignorePattern config

### PR DESCRIPTION
**Pull request by sinankeskin**
Hi. This PR adds ignorePattern config which sometimes we need it.

For example: I upload my map files to Sentry but I don't want to upload to my server.

Simply we can update env like this and this is done.

```js
ENV['simply-ssh'] = {
  ignorePattern: '**/*.map',
};
```

Thank you.

### CODE REVIEW

**Comment by ryedeer** [comment]
Hello!

Thank you for the PR! I think this config option can be useful.

It would be great if you could add some tests for this new behaviour, and then we can merge this. Thank you in advance!

**Comment by sinankeskin** [comment]
Hi.
Test added.

Thanks.

**Comment by sinankeskin** [comment]
Looks like minimatch RegExp doesnt work as expected. Changed to plain old RegExp.

**Comment by ryedeer** [comment]
Thank you for your contribution!

**Pull request merged**
